version:  '3'

networks:
    reverse_proxy:
      external:
        name: "reverse_proxy"

services:

  vue:
    build:
      context: ./
    ports:
      - "5001:5001"
    networks:
      - reverse_proxy
    environment:
      VIRTUAL_HOST: "ds.nuttapat.me"
      LETSENCRYPT_HOST: "ds.nuttapat.me"
      LETSENCRYPT_EMAIL: "webmaster@hackinteach.com"

